apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-app-state
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /root/trading
