apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-stock-data
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /root/trading/stock_data
